# Generated by Django 5.0.3 on 2024-03-29 12:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mood_api", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DailyLogs",
            new_name="DailyLog",
        ),
    ]
